### ISSUE TITLE
V3.0.0 Important Please read!

### ISSUE THREAD

**Issue by chanan** [chanan/BlazorStyled#102]
There is an issue with v3.0.0 that I have not been able to fix yet.

If you are using it by itself and you have no issues, you can ignore this.

When trying to add it to other libraries that use BlazorStyled, I ran into an issuse in compiling / linking where the project won't compile with an error message regarding System.text.json versions. Still haven't figured out the cause.

**Comment by chanan** [comment]
I opened an issue in the aspnetcore repo: https://github.com/dotnet/aspnetcore/issues/23126

**Comment by imtrobin** [comment]
I usually use the source code versions so I can change the dependencies versioning to avoid these kind of problems

**Comment by chanan** [comment]
@imtrobin Since I am not sure where that is coming from yet, you might have the same issue in the source version, but if you havent run into it yet, you are (hopefully) fine.
