### ISSUE TITLE
Css Priority

### ISSUE THREAD

**Issue by haydar-metin** [chanan/BlazorStyled#103]
Hey,

currently the `generated stylesheet` is inserted as the first child of `head`, however shouldn't it be inserted as the last child?

For example, if we have different stylesheets already loaded like bootstrap in the `head`. Then the `generated stylesheet` would still be the first child in the head and based on the precedence of css, bootstrap would override `blazorstyled`, if both wanted to change the style of the same element.

Maybe i overlooked something in the documentation, so is there a possibility to move the `generated stylesheet` to the bottom of the `head` so that it has a higher precedence? 

https://css-tricks.com/precedence-css-order-css-matters/

Thanks!

**Comment by chanan** [comment]
Currently there isn't a way. I a bit concerned about always putting as the last change as well, because then there is no way to override anything that is generated. I am open to suggestion on how to best handle this...

**Comment by pgrm** [comment]
@chanan @haydar-metin isn't this what the `data-blazorstyled-priority` attribute is for? - https://github.com/chanan/BlazorStyled/blob/30b23f61e8510f9b3af2e47bf9525c271f6d4939/src/BlazorStyled/Internal/Scripts.js#L145 - it seems like you can already now define a simple element in the header (even a `<style data-blazorstyled-priority="1"></style>` should work)

This seems to be [new in 3.0 alpha 3](https://github.com/chanan/BlazorStyled/commit/f72e49ef9a7a75a6f9aaf72cf92b88ef1ed14853#diff-89781bfdc63065ab86d129dbfc37f125R151) - maybe all that's lacking is mentioning it in the documentation? Or did I misunderstand that feature?

**Comment by chanan** [comment]
Close, but The priority attribute helps only within BlazorStyled itself. So if you have several style sheets (WithId) you can order them. 

It doesn’t help for style sheets outside of BlazorStyled.

**Comment by pgrm** [comment]
@chanan excuse my ignorance here, but looking at at the method `getOrCreateSheet` alone (and that might very well be the problem), could you please give me a hint, how that would differ? The way I read the method:

- if it finds any element with `data-blazorstyled-priority` attribute lower than the current priority, it appends below
  - it actually appends it below the first element of lower priority, so if you have multiple elements with varying priorities, you need to sort them by priority before calling this method, right? (I didn't dig that deep, just wondering if I'm understanding it correctly)
- if no matching element can be found (based on the attribute `data-blazorstyled-priority`) the element is inserted at the top

https://github.com/chanan/BlazorStyled/blob/30b23f61e8510f9b3af2e47bf9525c271f6d4939/src/BlazorStyled/Internal/Scripts.js#L177-L179

From this perspective, I'm missing the reasoning, why an element created by me manually would behave differently as a boundary, then an element created by BlazorStyled for the sake of ordering styles. 

Except of course, for the fact that this is currently an internal implementation detail, and not yet part of the public API of BlazorStyled and maybe shouldn't be relied upon. Other then that - what else am I missing, why it might not work?

**Comment by chanan** [comment]
The issue is this, I think:


if (!found) {
        head.insertBefore(styleEl, head.firstChild);
}

Which would be the most common case when there is only one BlazorStyled sheet. That always means that BlazorStyled will be the first stylesheet, so you can never override existing styles.

What I think we want is to allow the developer to append the style sheet to the end of the head when they choose.

**Comment by pgrm** [comment]
but you are setting found to true, once you've found a "matching" element:

https://github.com/chanan/BlazorStyled/blob/30b23f61e8510f9b3af2e47bf9525c271f6d4939/src/BlazorStyled/Internal/Scripts.js#L168

and the condition for a "matching" element is simply

https://github.com/chanan/BlazorStyled/blob/30b23f61e8510f9b3af2e47bf9525c271f6d4939/src/BlazorStyled/Internal/Scripts.js#L164-L167

this can be faked for any element, if you know the attribute name.

As a matter of fact, I've just tried it out and I was able to change the default location for the BlazorStyled element to any place I wanted, just by defining an `<style data-blazorstyled-priority="-1"></style>` in my head. 

Try it out for yourself, if you don't believe me. But I think this is the perfect solution to this problem. 

- You can control exactly where that style will show up 
- and it's no additional effort, just documenting an existing feature.

**Comment by chanan** [comment]
I am on my phone but I will try it tomorrow. Are you saying do something like this:

<head>
<style src=“my-base-styles.css”></style>
<style data-blazorstyled-priority=“-1”></style>
<!— BlazorStyled sheet will go here due to the line above —>
</head>

Yep that does sound like it will work, great idea!

**Comment by haydar-metin** [comment]
Thanks for the hint, using `<style data-blazorstyled-priority=“-1”></style>` as the last entry works!

**Comment by chanan** [comment]
Thanks @pgrm for the idea! I will document as soon as I fix #102
