### ISSUE TITLE
Remove javascript (insertRule) and use native blazor to update the styles

### ISSUE THREAD

**Issue by chanan** [chanan/BlazorStyled#17]
As pointed out in Gitter by SQL-MisterMagoo - if the JS is removed and the style tag is placed in the body then instead of using insertRule everything can be done without any JS.

This will be slightly slower when many styles change at once such as on BlazorTypography when switching themes, but the benefit is that there will be no JS needed in the project

See examples:

* CSB: https://github.com/SQL-MisterMagoo/HogwartsCSB
* SSB: https://github.com/SQL-MisterMagoo/HogwartsSSB

**Comment by SQL-MisterMagoo** [comment]
Performance of inserting styles is definitely something I haven't measured.

**Comment by chanan** [comment]
Got CSB working, SSB is being a pita

**Comment by SQL-MisterMagoo** [comment]
Are you just rendering a component in both cases?

**Comment by chanan** [comment]
Yes but one is causing the other to update, still investigating exactly what the problem is

**Comment by chanan** [comment]
Found the problem, looks like a bug in Blazor which I will report.

If I do this:

```
<style>@(await Html.RenderComponentAsync<TempStyle>())</style>
```

Where `TempStyle` is:

```
html {
    color: red;
}
```

Then I get:

```
blazor.server.js:15 [2019-07-26T14:43:18.806Z] Error: There was an error applying batch 2.
e.log @ blazor.server.js:15
blazor.server.js:15 [2019-07-26T14:43:18.930Z] Error: System.AggregateException: One or more errors occurred. (Error: No element is currently associated with component 0)
 ---> Microsoft.AspNetCore.Components.Browser.Rendering.RemoteRendererException: Error: No element is currently associated with component 0
   at Microsoft.AspNetCore.Components.Rendering.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
   --- End of inner exception stack trace ---
```

And in the DOM:

```
blazor.server.js:15 [2019-07-26T14:43:18.806Z] Error: There was an error applying batch 2.
e.log @ blazor.server.js:15
blazor.server.js:15 [2019-07-26T14:43:18.930Z] Error: System.AggregateException: One or more errors occurred. (Error: No element is currently associated with component 0)
 ---> Microsoft.AspNetCore.Components.Browser.Rendering.RemoteRendererException: Error: No element is currently associated with component 0
   at Microsoft.AspNetCore.Components.Rendering.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
   --- End of inner exception stack trace ---
```

Moving the `style` tag into `TempStyle` fixes the problem

**Comment by chanan** [comment]
Created issues:

SSB Bug: https://github.com/aspnet/AspNetCore/issues/12611

CSB Feature request: https://github.com/aspnet/AspNetCore/issues/12613

**Comment by chanan** [comment]
To fix the "link issue convert links that look like:
```
<link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
```
to a css import:
```
@import url('https://fonts.googleapis.com/css?family=Roboto&display=swap');
```

**Comment by chanan** [comment]
Done in 1.0.0-preview7-02
