### ISSUE TITLE
Doesn't work on server side Blazor

### ISSUE THREAD

**Issue by alexandrereyes** [chanan/BlazorStyled#2]
Steps do reproduce:
1) Create a new server side blazor project (template from vs 16.2 preview)
2) On ConfigureServices, add the di:
```
services.AddRazorPages();
services.AddServerSideBlazor();
services.AddBlazorStyled(isDevelopment: true);
services.AddSingleton<WeatherForecastService>();
```
when you try to run the project:
InvalidOperationException: Cannot consume scoped service 'Microsoft.JSInterop.IJSRuntime' from singleton 'BlazorStyled.Internal.StyledJsInterop'.

**Comment by chanan** [comment]
I haven't tried server side blazor apps at all yet. Looking into it now

**Comment by alexandrereyes** [comment]
In my opinion, server side blazor should be the main focus on the community, since it'll be release in next September. 
Client side blazor will release only in 2020.

**Comment by chanan** [comment]
Checked the docs and I dont see a mention about it, asking in the Gitter room

**Comment by alexandrereyes** [comment]
https://medium.com/capgemini-dynamics-365-team/future-of-net-net-5-microsoft-build-2019-from-a-net-developer-point-of-view-7a1158fb0691

Client side Blazor will be release probably in September 2020, with .net framework 5

**Comment by chanan** [comment]
First problem is fixed.

Facing new problem now, the js file is not being sent from the library to the server side app.

**Comment by alexandrereyes** [comment]
Try this link https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/
Find for static files

**Comment by chanan** [comment]
On the right track, yes. I was still using the older content folder which strangely still worked for CSB apps. Still have something not quite right as it is not finding `_content\BlazorStyled\styled.js`

**Comment by chanan** [comment]
Thanks to help from the nice folks on Gitter, got a blank library, CSB, and SSB project all working. Should be able to get a new build out tonight or early tomorrow morning

**Comment by chanan** [comment]
This now works. Will make a build soon and update the docs for SSB differences. Which needs to work like this:

```
<div class="@div">Test</div>

@code {
    private string div;


    protected override async Task OnAfterRenderAsync()
    {
       div = await Styled.Css("background-color: pink;");
       StateHasChanged();
    }
}
```

**Comment by chanan** [comment]
Fixed!

I am going to open a new issue to look into ways to pre render more stuff on the server and send it down to the client, not 100% sure its possible, but something to think about.
