### ISSUE TITLE
Documentation site code examples boxes all have errors

### ISSUE THREAD

**Issue by VR-Architect** [chanan/BlazorStyled#22]
Excellent project that is exactly what I needed! I am not able to figure out how to use it as the documentation website is showing errors in all the code sample boxes. 

Thanks again for the excellent package. You should see if Microsoft could add it to the next Blazor Preview version!

**Comment by chanan** [comment]
Yes I know. Sadly I made a major update to BlazorStyled while traveling for a day and stupidly I forgot my laptop power cord at home. I have the documentation almost all ready to go but can’t update the site. It will be updated tomorrow though! Sorry, that was my foolish mistake!

**Comment by VR-Architect** [comment]
No worries. It happens to me too :)  In the mean time, do you mind sharing the google font snippet for the razor page? I used your code from the server example. BTW, I racked my brains for 4 days trying to figure out a solution to switching google fonts on a razor page. You rock!

**Comment by chanan** [comment]
Fixed now, sorry about that.

I will be updating the docs with more info (and better mobile support) in the next day or two
