### ISSUE TITLE
Code for setting a google font 

### ISSUE THREAD

**Issue by VR-Architect** [chanan/BlazorStyled#23]
Can you please give a sample of how to set the google font on the razor page variable?

**Comment by chanan** [comment]
Not sure what you mean exactly. This is the way google fonts work now:

```
<StyledGoogleFont Name="Geostar" Styles="normal" />

<Styled @bind-Classname="@geostar">
    font-family: Geostar;
</Styled>

<p class="@geostar">This is the Geostar font</p>

@code {
    private string geostar;
}
```
Are you looking for something more than that?
