### ISSUE TITLE
How to use @font-face via C#

### ISSUE THREAD

**Issue by VR-Architect** [chanan/BlazorStyled#27]
I see the example for fonts here: https://blazorstyled.io/fonts

What I need is to dynamically set this as a variable and not in a style tag:

```
    @font-face {
        font-family: 'Indie Flower';
        font-style: normal;
        font-weight: 400;
        font-display: swap;
        src: local('Indie Flower'), local('IndieFlower'), url(https://fonts.gstatic.com/s/indieflower/v10/m8JVjfNVeKWVnh3QMuKkFcZVaUuH.woff2) format('woff2');
        unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
    }
        font-family: {'Indie Flower'};
```

For my web page, the user has a dropdown to select 1 of 940 Google fonts. When the font selection changes, I set a variable to the appropriate value like this:

```
<div style="@myFont">
    Hello
</div>

code{
        public string myFont { get; set; }
        private string fontFamily { get; set; }
        private string fontStyle{ get; set; }
        private string fontWeight { get; set; }
        private string fontDisplay { get; set; }
        private string fontUrl { get; set; }
        private string fontFormat { get; set; }
        private string fontUnicodeRange { get; set; }

        public void FontOnChange(UIChangeEventArgs args)
        {
            fontFamily = "Indie Flower";
            fontStyle = "normal";
            fontWeight = "400";
            fontDisplay = "swap";
            fontUrl = "https://fonts.gstatic.com/s/indieflower/v10/m8JVjfNVeKWVnh3QMuKkFcZVaUuH.woff2";
            fontFormat = "woff2";
            fontUnicodeRange = "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD";

            myFont = $@"    @font-face {{
        font-family: '{fontFamily}';
        font-style: {fontStyle};
        font-weight: {fontWeight};
        font-display: {fontDisplay};
        src: local('{fontFamily}'), local('{fontFamily.Replace(" ", "")}'), url({fontUrl}) format('{fontFormat}');
        unicode-range: {fontUnicodeRange};
    }}
        font-family: {fontFamily};";
        }
}
```

Is this possible  but using BlazorStyled? It's not possible with plan Blazor.

**Comment by chanan** [comment]
Do you need the full power of Font face or ok with using Google fonts?
If you want to use google fonts only, is page do what you want (Check the typeface drop down, you can ignore the other theme stuff): https://chanan.github.io/BlazorTypography/

**Comment by VR-Architect** [comment]
ohhhhh, that is a very nice package also! I am fine with just Google fonts, but need to set them via code as the user changes the value. I see this in the code but not sure how to apply it to a div onchange.

```
            BlazorStyled.GoogleFont gf = new BlazorStyled.GoogleFont
            {
                Name = "Indie Flower",
                Styles = new List<string> { "normal" }
            };
```

**Comment by chanan** [comment]
I will answer your second question first - Yes! In fact that new BlazorStyled site does just that! If you look here: https://github.com/chanan/BlazorStyled/blob/master/src/SampleCore/Shared/MainLayout.razor#L127 - I "init" the styles with BlazorTypography, then the rest of that file (and the rest of the site really) - I either override some html elements directly or I use "classes" to override specific things.

For your first question, yes should be doable. I think you are asking how do I know what variable to put for font name?

First I would grab the two file from here: https://github.com/chanan/BlazorTypography/tree/master/src/SamplePages/Fonts

FontManager contains all the google fonts (Note: I chose to hard code those in there, but you could rip that out and replace it with an api call to fonts.google.com if you want).

You can then use Font Manager to create a dropdown in your page just like BlazorTypography does:
Pseudo code:
```
<select>
@foreach(var font in fontManager.Fonts)
{
   <option value="@font.name">@font.name</font>
}

<div class="@myclass">hello</div>
```

You would need to add the bind stuff and listen to the onchange of the select

and:

```
@code {
void onchange(){
 //Assuming you had a bind called fontname
BlazorStyled.GoogleFont gf = new BlazorStyled.GoogleFont
            {
                Name = fontname,
                Styles = new List<string> { "normal" }
            };
Stlyed.AddGoogleFont(gf);
myclass = Styled.Css("font-family: " + fontname +";");
}
}
```

Something like that should work. Let me know either way

**Comment by chanan** [comment]
@VR-Architect Were you able to use the code I showed you to achieve what you wanted to do?

**Comment by VR-Architect** [comment]
Hi @chanan 

I get an error on the last two lines: 

- Style does not contain a definition for AddGoogleFont 
- Style does not contain a definition for Css

BTW, love how you hard coded those values. I was wondering how I was going to get all that into hard coding. I did my original using an enum. BTW, I added a sort to the font manager:

`Fonts = temp.OrderBy(o => o.Family).ToList();`

The razor code worked perfectly. Here is my change event.
```
        protected async Task FontChanged(UIChangeEventArgs args)
        {
            string fontname = args.Value.ToString();

            BlazorStyled.GoogleFont gf = new BlazorStyled.GoogleFont
            {
                Name = fontname,
                Styles = new List<string> { "normal" }
            };
            Styled.AddGoogleFont(gf);  // error here
            string myclass = Styled.Css("font-family: " + fontname + ";"); // error here
        }
```

Thanks again for the excellent project!

**Comment by VR-Architect** [comment]
Using BlazorStyled v1.0.0-preview7-05

**Comment by chanan** [comment]
If Visual Studio can't find AddGoogleFont and Css, then its not recognizing the type of Styled - how did you define it?

If you want, you can post your project somewhere and I can check it out.

And thanks, I use emotion.js with React - so I tried to make a similar project for Blazor.

**Comment by VR-Architect** [comment]
I didn't define Styled as I copied your sample code above. It's namespace is BlazorStyled.Styled. Did I miss something to define it?

**Comment by chanan** [comment]
Yes, it to use the API it needs to be injected.
If you are using a component defined in a razor file, you inject it like so: `@inject IStyled Styled`
If you are defining a component in a C# class you inject it like so: `[Inject] private IStyled Styled { get; set; }` (Constructor injection also works I think).

**Comment by VR-Architect** [comment]
LOL, I just figured that out from your docs.

Sorry about that.

**Comment by chanan** [comment]
No worries, I am here to help!

**Comment by VR-Architect** [comment]
Hey,
I want to thank you very much. All worked as expected. Too awesome!

VR Architect

**Comment by chanan** [comment]
That's great! I am going to close this issue, but please feel free to open another one if you have more questions or problems!
