### ISSUE TITLE
Link to a css file

### ISSUE THREAD

**Issue by alexandrereyes** [chanan/BlazorStyled#34]
What do you think about: `<Styled src="myStyle.css" />` ?

this way, I can segregate CSS from razor file, like @inherits to use a base class.
Another benefit is to have intelisense on CSS 

the result would be:
![image](https://user-images.githubusercontent.com/729956/62870653-5d992000-bcf0-11e9-8d87-c73048319e18.png)

**Comment by chanan** [comment]
Not sure how this would work exactly, can you supply more details?

**Comment by alexandrereyes** [comment]
Instead using style inside the component razor file, you'll have the CSS in another file.

**Comment by chanan** [comment]
Right now there is no way to pretender the css. However, I will see if it is possible to link to css file that is a razor file.

**Comment by chanan** [comment]
This doesn't look possible at this time. Maybe, if in the future I can figure out a way to pre-render all the css in the app, I can create a css file you can link to. I will leave this open, but this is a long term item

**Comment by alexandrereyes** [comment]
Hey @chanan what's your thoughts about this? https://github.com/alexandrereyes/BlazorScopedCss

**Comment by chanan** [comment]
Very nice project!

**Comment by chanan** [comment]
Closing this, let me know if you have more questions
