### ISSUE TITLE
[Preview 8] BlazorStyled and Syncfusion don't work together

### ISSUE THREAD

**Issue by VR-Architect** [chanan/BlazorStyled#40]
I upgrade to today's version for both.

Syncfusion needs this to work:
`endpoints.MapBlazorHub<App>(selector: "app");`

BlazorStyled needs this to work:
`endpoints.MapBlazorHub();`

How to get both to work together? I can only get one to work at a time.

**Comment by chanan** [comment]
I haven’t tried it but suncfusion should be able to work with the way BlazorStyled is. Have you tried it?

I won’t be back home till Friday. Took my girl to college

**Comment by VR-Architect** [comment]
Yes, I used them both in Preview 7 and now Preview 8.  I have been using Syncfusion controls since the beginning. The issue only came up with I had to change to this:

`endpoints.MapBlazorHub();` 

with BlazorStyled Preview 8. They do not work together if we have to change that.

**Comment by chanan** [comment]
Hi @VR-Architect, There is a workaround! You don't have to place the style tag in the head. I will update the docs for this alternate solution but in the mean time, to get you going here is what you need to do (Posting a link to a working project at the end of these instructions as well):

1. You don't need to change the _Host.cshtml file, leave it as it is.
2. You don't need to change `Configure` in the `Startup.cs` file, you can leave it like so: `endpoints.MapBlazorHub<App>(selector: "app");`
3. You still need to add: `services.AddBlazorStyled();` in `ConfigureServices` in `Startup.cs`
4. In your main layout add: `<ServerSideStyled/>`

That's it, everything should work! Here is a working sample with a red paragraph generated by BlazorStyled and the Calendar control from the Getting Started in the SyncFusion docs: https://github.com/chanan/BlazorStyledPlusSyncFusion

Thanks for bringing this to my attention. This might also work in Server pre-render scenarios. I will have to check it out. As usual, I will leave this issue open in case you can get it working, please let me know either way.

**Comment by VR-Architect** [comment]
Wow! You continue to impress. That is more elegant solution. Thanks again!

**Comment by chanan** [comment]
Docs updated: https://blazorstyled.io/alternate-server-side-install

**Comment by chanan** [comment]
In preview 9 this might have been fixed to work the "original way" I will retest this tomorrow. see here: https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-9/#multiple-components-in-views-or-pages
