### ISSUE TITLE
Server side project requires alternative methodology -- A couple of ?

### ISSUE THREAD

**Issue by MarkStega** [chanan/BlazorStyled#43]
I have a Blazor project underway that I am adding BlazorStyled. If I do the change to _Host.cshtml
```
    @(await Html.RenderComponentAsync<BlazorStyled.ServerSideStyled>())
```
several of my components fail to function (namely a modal popup and all derived from that. I can get everything to work using the ServerSideStyle component.

1) Do you know what the interference issue is? I have control over my components so if needed I can change them.
2) I have only one MainLayout.razor in a razor class library that is used by both a server side implementation as well as a client side implementation. The ServerSideStyle component does not seem to hurt on client side execution. I see that there is a similar ClientSideStyle component which is close in implementation. I seem to need the index.html addition for client side to work. Should I be composing the MainLayout via BuildRenderTree to avoid the ServerSideStyle component when I am client side or is my emperic observation of 'it doesn't hurt' ok?

**Comment by chanan** [comment]
Closing this as it seems you got it all working. Let me know if you have other questions or issues
