### ISSUE TITLE
media query with fixed classname

### ISSUE THREAD

**Issue by cerkoid** [chanan/BlazorStyled#47]
There is a bug with Styled.CSS API method when you use it like Styled.CSS("xsDown", body)
It creates inline style like 

.xsDown{@media only screen and (max-width:600px) { display: none !important;}

and not 

@media only screen and (max-width:600px) { .xsDown{ display: none !important;} }

With <Styled> component it's the same.

Works correct when binding classname with @bind-Classname though…

BTW great work

**Comment by chanan** [comment]
Hi @cerkoid sorry for the late reply.

Do you mean you are doing:

```
Styled.Css("xsDown", "@media only screen and (max-width:600px) {display: none !important; }");
```

**Comment by cerkoid** [comment]
I don't have a sample any more, i made a workaround using static css file... But just try to declare style like 
`<Styled Classname=".xsDown">
  @media only screen and (max-width : 600px) { display: none !important; }
</Styled>`
it creates strange css syntax, but if you do it like
`<Styled bind-Classname="some local variable">
  @media only screen and (max-width : 600px) { display: none !important; }
</Styled>`
it creates correct CSS style

**Comment by chanan** [comment]
The following two ways should do what you want (or close to it in one case):

1. Drop down to just using `Styled`:

```
<Styled>
    @@media only screen and (max-width : 600px) {
        .xsDown {
            display: none !important;
        }
    }
</Styled>
```
This will out the exact CSS you want.

2. You can use the built in media queries but it wont be the exact media query you want:

```
<Styled MediaQuery="MediaQueries.Tablet">
    .xsDown {
        display: none !important;
    }
</Styled>
```

Which will output:
```
@media only screen and (max-width:768px){.xsDown{display:none !important;}}
```

Let me know if this solves this issue

**Comment by chanan** [comment]
Closing this, let me know if you have more questions
