### ISSUE TITLE
CSS vendor prefixes

### ISSUE THREAD

**Issue by cerkoid** [chanan/BlazorStyled#48]
How can one use vendor prefixes?

<Styled Classname=".test">
  display: grid;
  display: -ms-grid;
</Styled>

results in CSS
.test {
  display: -ms-grid;
  display: -ms-grid;
}

**Comment by chanan** [comment]
Thanks for the two big reports. I will check then out tonight after work

**Comment by chanan** [comment]
Can you supply the exact line you are running please? Also, if you can, what the output should be.

**Comment by cerkoid** [comment]
So given razor syntax:
<Styled Classname=".rlG.PFl">
  display: -ms-grid;
  display: grid;
  flex-shrink: 0;
</Styled>

result should be like:
.rlG.PBL {
  display: -ms-grid;
  display: grid;
  flex-shrink: 0;
}
and not

.rlG.PBL {
  display: grid;
  display: grid;
  flex-shrink: 0;
}

**Comment by cerkoid** [comment]
In previous comment razor syntax is like this (github stripped tags):
`<Styled Classname=".rlG.PFl">
  display: -ms-grid;
  display: grid;
  flex-shrink: 0;
</Styled>`

**Comment by chanan** [comment]
@cerkoid When I ran:

```
<Styled Classname=".rlG.PFl"> display: -ms-grid; display: grid; flex-shrink: 0; </Styled>
```

I did get the correct output:

```
<style><!--!-->
        <!--!-->.rlG.PFl{display:-ms-grid;display:grid;flex-shrink:0;}<!--!-->
</style>
```

Was there something else on the page that you had that might have caused that in some way?

**Comment by chanan** [comment]
Closing this, let me know if you have more questions
