### ISSUE TITLE
Does with work with Position elements also?

### ISSUE THREAD

**Issue by DataJuggler** [chanan/BlazorStyled#49]
I read the docs, but didn't see any examples involving position.

And bonus question, how does this work under the hood? Does it take the Styled Attributes and add it to a virtual css file?

I love Blazor, I just feel like there is a hook missing to be able to programmatically refer to elements and get / set values of attributes and I could forever get rid of javascript.

**Comment by chanan** [comment]
Positioning should be like any other CSS property and should work. I think I might have some examples in the hamburger menu used in the site when in phone viewport. I will check and paste the link if it’s used. 

The way it works is it “prints” out the CSS to the tag in the head. If you look in dev tools, expand the head tag and you should see a style tag with all your CSS. 

Yes to read the dom you would need JavaScript. You can create a C# that masks the call though

**Comment by DataJuggler** [comment]
Thank you for the reply. I will try again as my first test was probably setup wrong.
