### ISSUE TITLE
Question: How did you create the docs at https://blazorstyled.io?

### ISSUE THREAD

**Issue by DataJuggler** [chanan/BlazorStyled#50]
Sorry to ask an off topic question, but I really like the format of your documentation.

Is that a template or something, or did you create all that by hand? I need something like that for my projects.

Many Thanks

Corby

P.S. I searched YouTube for some of your projects and couldn't find anything, do you have a channel?

**Comment by chanan** [comment]
Hi,

No, sorry I dont have a you tube channel.

I used a modified version of a github SPA template (Can't find the exact one anymore).

If you look in /docs folder, the relevant files are index.html and 404.html. You should also have a .nojekyll for some reason.

Once that is setup, I simply copy the folders from \bin\Debug\netstandard2.0\dist and place them in /docs.

Hope that help!

**Comment by DataJuggler** [comment]
Thanks for the reply, I will see if I can follow the instructions. 

Your code is so popular you should making some videos.

**Comment by chanan** [comment]
Thanks, I will give it some thought! :)
