### ISSUE TITLE
Your Docs List RenderModeAsync without a parameter

### ISSUE THREAD

**Issue by DataJuggler** [chanan/BlazorStyled#51]
To get a new project to compile, this line has to have RenderMode parameter specified:

@(await Html.RenderComponentAsync<BlazorStyled.ServerSideStyled>(RenderMode.ServerPrerendered))

You get an error about RenderModeAsync does not have any overloads with zero parameters if you don't have something there.

I am not sure if Server or ServerPrerendered is the correct option.

**Comment by chanan** [comment]
I will update the docs. Sorry about that, it was done prior to the time RenderComponentAsync had a required param

**Comment by DataJuggler** [comment]
No apologies are necessary. Blazor is new and I expect change as sometimes even Microsoft has to go back to the drawing board to get it right. I was just trying to help the next person that comes along.

Thanks

**Comment by chanan** [comment]
Going to reopen this till I update the docs, otherwise, I will forget :)
