### ISSUE TITLE
invalid service collection

### ISSUE THREAD

**Issue by mcc85s** [chanan/BlazorStyled#52]
![image](https://user-images.githubusercontent.com/44849131/72213581-3b821480-34bf-11ea-8d1f-a60e938fa4b1.png)

I am able to get this to work if I choose the server side only, however if I choose webassembly, no go. This would be great to use because between jsinterop and this... this method would be more of a preferred choice considering some of blazor's limitations.

**Comment by chanan** [comment]
It looks like that your IServiceCollection is called services, so `services.AddBlazor` should work. Let me know.

**Comment by mcc85s** [comment]
you can close this issue. I spent a whole week trying to get JSInterop to work the way I wanted
if you care to check it out... this is what I was trying to do.
https://youtu.be/Z99zsCwYhWk

haven't gotten it to work yet... thanks for your response though.

**Comment by chanan** [comment]
I watched the video, but not sure what issue you were having. Was it a problem with BlazorStyled? I can try to help if you explain the issue and post some code.

Or I can close the issue if you want.

**Comment by mcc85s** [comment]
That video uses strictly javascript and css, that is not actually running Blazor yet.

I couldn't get BlazorStyled working, nor what I'm doing with the scaling natively in Blazor.

When I first heard of your project, I thought perhaps it would be able to dynamically scale the CSS content, which is what I'm attempting to do.

**Comment by chanan** [comment]
BlazorStyled doesnt dynamically scale your CSS that's true, but it does allow you to dynamically change your CSS in code so you could do something like this (psudeo code):

```
<Styled @bind-Classname="@myFont">
  font-size: @myFontSize
</Styled>

<p Classname="@myFont">
 This font will change size dynamically
<p>

@code {
  @private string myFontSize = "16px";

  private sub OnIntialize() {
    if(isMobile) myFontSize = "12px";  //Note this is pseudo code
  }
}
```

For an example of changing font size on a button click you can see here: https://blazorstyled.io/composition (The purpose of the page is actually dynamic class composition but just so happens the example uses font size).

Also, if you want to just drop something in that sets up element sizes and much more, you can see this project: https://github.com/chanan/BlazorTypography which uses BlaozrStyled under the hood to setup a bunch of preset defaults for you based on (overrideable themes). The demo page is: https://chanan.github.io/BlazorTypography/

**Comment by mcc85s** [comment]
Yes I see that's very powerful indeed.

I'll keep that in mind. Thank you!
