### ISSUE TITLE
Can you explain how your short example works where @hover = EmptyString please?

### ISSUE THREAD

**Issue by DataJuggler** [chanan/BlazorStyled#53]
I am just trying to better understand how this works, but from looking at your example, isn't @hover empty string or null since it was never initialized?

In a real example with other classes, wouldn't you have to set @hover to something?

My more than likely flawed HTML interpreter in my brain outputs this as class="", is that correct?

Thanks.

**Comment by chanan** [comment]
It sounds like you are referring to the snippet on the home page of https://blazorstyled.io ?

```
<Styled @bind-Classname="@hover">
    label: hover-example;
    padding: 32px;
    background-color: hotpink;
    font-size: 24px;
    border-radius: 4px;
</Styled>

<Styled Classname="@hover" PseudoClass="PseudoClasses.Hover">
    color: @color;
</Styled>

<div class="@hover">
    Hover to change color.
</div>

@code {
    private string hover;
    private string color = "white";
}
```

The first tag: `<Styled @bind-Classname="@hover">...</Styled>` will "bind" the contents of the tag to the variable named "hover". So after that tag gets executed hover will be initialized to that css snippet.

After the second tag executes hover.hover (pseudo class hover of a css class named hover) will be set to the contents of that tag (`<Styled Classname="@hover" PseudoClass="PseudoClasses.Hover">`)

Lastly, the div gets rendered with the class name that point to the hover class name that was generated by Styled.

I hope hat answered your question. If not let me know.

**Comment by DataJuggler** [comment]
Yes it does. The part that wasn't obvious to me is what you just explained, the part about 'after that the tag gets executed hover will be initialized to that css snippet'.

So in effect you are saying this:
Set @hover = the string that make up the CSS contents of the Styled element.

Some things take me longer to understand, I figured out quickly that I can't modify the variable name or everything quits working.

Thanks for the explanation and this library.

I love being able to modify CSS dynamically, as before Blazor and BlazorStyled I only knew how to change class names via JavaScript. 

`<Styled @bind-Classname="@ProfileImageStyle">
    background-image: url('@ProfileImageUrl');
    width: 256px;
    height: 256px;
    transform: scale(0.5);
    transform-origin: left;
    position: fixed;
    top: 40%;
</Styled>`

**Comment by chanan** [comment]
Great, glad you find the library useful! :)
