### ISSUE TITLE
Question: How do I pronounce your name?

### ISSUE THREAD

**Issue by DataJuggler** [chanan/BlazorStyled#55]
I finally finished my Blazor sample and I am making a short video today. I added a simple animated car race to demonstrate some of the things you can do with BlazorStyled. 

I don't want to butcher your name if I can help it. 

My guess is:
Chanan - kind of like Shannon but with a CH at the beginning and a 'an' sound at the end.
Braunstein: Brawn Stine is my guess, or maybe it is steen?

Thanks,

Corby

**Comment by DataJuggler** [comment]
I published the video: https://youtu.be/frtetHgfdIo

I hope I did your name justice or didn't butcher it too badly.

Thanks

**Comment by chanan** [comment]
Awesome video, I will post it on the site shortly!

**Comment by chanan** [comment]
Doc update tracked here: https://github.com/chanan/BlazorStyled/issues/56
