### ISSUE TITLE
Any way to utilize partial classes?

### ISSUE THREAD

**Issue by niem94** [chanan/BlazorStyled#71]
I would love to use partial classes for BlazorStyled, as that would allow me to do the following:

ClassName.razor
--> ClassName.razor.code.cs
--> ClassName.razor.styles.cs

So is it possible to define styles in a class?

**Comment by chanan** [comment]
That is not valid in Blazor framework, unless I am misunderstanding what you mean, so I can't help you there. But you can to three things that are valid.

1. You can have a code behind for a razor component where you put the Styled tag as well as other markup in your razor file and the logic in your class. 
2. You can create a component with your Styled tags and inside of it put another Component with you other markup and logic.
3. You can have a base class for your component and inside of the base class you can use IStyled and do your styles in BuildRenderTree

Does that help?

**Comment by niem94** [comment]
So actually partial classes are supported since 3.1. They are implemented the same way as Base Classes except they are not inherited, and uses the partial keyword instead. There are also some differences in the functionality, but I'm not too familiar with that.

I figured it out, and it works like a charm. I shared a simple example below on how this works (now I just want file nesting in vscode, but I can only dream): 

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/26203420/76580307-c4bdc380-64cf-11ea-8fff-c4856f1a5ce7.png">

**Comment by chanan** [comment]
Glad you figured it out! What you did is more or less what I mean by my 1 suggestion, but what I didnt know is that you can have file names the way you have them.

You know you can also have a "real razor" and a cs file something like this (Pesudo code because it is a lot of typing :)  )

Hyperlink.cs:

```
partial class Hyperlink {
  private string _myclass;
  [param] public RenderFragment ChildContent { get; set; }
  //Rest of params and logic goes here
}
```

Hyperlink.razor

```
<a href={some param} class="@_myclass">
   @ChildContent
</a>
 <Styled @bind-Classname="@_myclass">
   //css goes here
 </Styled>
```

I have been using that style lately - it is a really nice and easy to look at.

Hey, if you have a second, what are you using BlazorStyled for? Any feature suggestions?

**Comment by niem94** [comment]
Thanks, yeah I think it is pretty neat that it allows for multiple partial classes. It helps in keeping the clutter away :-) 

I actually used that style before, but I prefer my css in a separate file from my markup and code to clearly separate concerns.

Im using BlazorStyled for a project i'm making for Southern University Denmark. It is a website where one can create Business Models over big to small markets. It concerns itself with stakeholders and their associations. 

Feature wise I really like BlazorStyled, it solves not having sass, and honestly I'm not really missing anything. One thing I've been confused about myself though, is @bind-Classname. I don't like that it requires multiple <Styled> tags. I would much rather prefer something like this for scoped css (which is much more similar to native css):

```
<Styled>
    @_myFirstClass {
        // styles
    }
    @_mySecondClass {
        // styles
    }
</Styled>
```

I reckon that's hard to do though.

**Comment by chanan** [comment]
You are right, I dont think I can do what you mention in your code snippet because the framework needs to set the the class name (@_myFristClass, @_mySecondClass) and notify Blazor the variable changed (which is what bind does). But just because I dont see a way to do that right away doesn't mean its not possible :) So I will think about it for a bit.

Just so I get more info from you. What you described in your snippet is:

```
<Styled @bind-Classname="@_myFirstClass">
  //Styles
</Styled>

<Styled @bind-Classname="@_mySecondClass">
  //Styles
</Styled>
```

Would something like this work for you (keep in mind no clue if it can be done or not):

```
//Note: bind-Classnames plural
//Note 2: You dont have to define the list in the @() of course, just putting it here to show what the list would contain
<Styled @bind-Classenames=@(new List { @_myFirstClass, @_mySecondClass }>
    @_myFirstClass {
        // styles
    }
    @_mySecondClass {
        // styles
    }
</Styled>
```

Reopening this so I dont lose track of this thread. Will close it again later

**Comment by niem94** [comment]
Glad that you liked my idea. What you propose here would indeed be a good solution for it! I like it :-)

**Comment by chanan** [comment]
Added a new issue for this. Closing this now. Thanks again!

**Comment by chanan** [comment]
@niem94 Check out the new GlobalStyles in v2.2.0 (I added an example of it in the documentation site) - It might also be useful for defining styles in a separate file.

**Comment by niem94** [comment]
@chanan that seems very useful for a lot of cases!  How do you propose it is used in a separate file? :-)

**Comment by chanan** [comment]
I have one example in the docs site under Global Styles in the nav

Basically it allows you to define a style in one file (obvious example would be MainLayout.cs) and give it a name. 

Then later in your component you can grab that name and directly apply it to a class attribute. 

Can be useful in some cases but not all. If your styles are dynamic or depend on params in your component then it won’t help. 

So it’s good for utility classes and some stuff that won’t change that you can define upfront.

**Comment by niem94** [comment]
Oh I misunderstood you there. I thought you meant in a separate file like with partial classes or base classes ;-) I do recognise the usefulness of the feature itself 🥇 It is awesome to have some place to define global styles such as your above examples :-) Thanks for sharing!
