### ISSUE TITLE
Documentation Site

### ISSUE THREAD

**Issue by grserwe** [chanan/BlazorStyled#73]
I'm unable to get to the documentation site.  I either get stuck on the Loading... and eventually get the page  is not responding out or I get an unhandled error has occurred.    https://blazorstyled.io/

**Comment by chanan** [comment]
What browser / os?

**Comment by grserwe** [comment]
I attempted to use Chrome on Windows 10.

                Odd… I just tried Microsoft Edge and it works.

                I also tried from my android phone running chrome and it failed.

                Lastly I tried it using the silk browser on a amazon tablet (android)

                The fact that it works for me on Edge makes me think it’s strange problem on my end.  Sorry to bother you.  I’ll try and figure out what is going on from the none edge browsers.


Gregg Serwe

**Comment by chanan** [comment]
Hi Gregg,

I just tested on windows 10 with chrome Version 80.0.3987.132 (Official Build) (64-bit) and it loaded.

What is the exact error in the console you are getting?

**Comment by grserwe** [comment]
Very strange indeed.  I was getting an out of memory error from WASM.  Shut everything down and rebooted.  Works on both browsers now.  Thank you for the follow up. 

Also, thank you for an awesome project!

**Comment by chanan** [comment]
No problem!

I do know that there is a bug in mono regarding memory issue, I will try to find it again (I hit it from time to time too).

Out of curiosity: what project are you building with BlazorStyled, and are there any features you feel are missing?

**Comment by grserwe** [comment]
I’m building a personal website for keeping track of various things such as addresses/recipes.  Another project includes a home automation manager.                 At this point I haven’t run into any features that I feel are missing.                 From the web application side I came from angular and jumped onboard blazor as soon as I could.  What I disliked about blazor was having to store all the css in site.css (or some other external css file).  I loved the feature in angular of having styles localized to the component.  A google search later and I found your solution which has filled the role I was looking for perfectly.           Gregg Serwe From: Chanan BraunsteinSent: Friday, March 13, 2020 10:18 AMTo: chanan/BlazorStyledCc: grserwe; State changeSubject: Re: [chanan/BlazorStyled] Documentation Site (#73) No problem!I do know that there is a bug in mono regarding memory issue, I will try to find it again (I hit it from time to time too).Out of curiosity: what project are you building with BlazorStyled, and are there any features you feel are missing?—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by chanan** [comment]
Thanks for the info Gregg! Please share the home automation manager when you have it working - its a personal of interest for me - I have tons of hue light bulbs! :)

If you ever have any suggestions for feature please reach out to me. Also did you see you can add Google fonts with a tag?

**Comment by grserwe** [comment]
I will check out the google fonts feature now that I can reach the documentation site again :)

If I run across a feature that I'd like to see, I'll certainly let you know.

I'd like to get your opinion  on something however.  The home automation manager project has multiple devices which all have some common styles.  Currently what I have is a static "GlobalStyles" class that contains strings with the common styles.  Each device component then references the GlobalStyles such as:

```
<div class="@deviceNameStyle>Testing</div>

<Styled @bind-Classname="@deviceNameStyle">
    @GlobalStyles.DeviceNameStyle
</Styled>
```

This is repeated for every device component type.  Is this the best way or is there a way to directly reference the <Styled...> across multiple components so I don't have to recreate the

```
<Styled @bind-Classname="@deviceNameStyle">
    @GlobalStyles.DeviceNameStyle
</Styled>
```

for every type of device.  (let me know if that doesn't make sense).

**Comment by chanan** [comment]
Right now, you will need to register it in both places (or some sort of include. The good news it will detect that it is the same exact class and will not enter duplicate styles and will return the same exact class name. The bad news is of course you need to enter it in twice (or some sort of global include).

The issue is to figure out a way to define a style in lets say MainLayout.cs and then get that class name down to your component defined somewhere else. Theoretically, Those styles are already there because IStyled is a scoped object that can be injected - so we are half way there. The problem is making something like `@GlobalStyles.MyClass` work - and make sense since class names are generated. I have no thoughts about that part yet. But I will add it to the features list. Thanks for the feedback!

**Comment by grserwe** [comment]
Thanks again for the response and explanation.   It's not difficult to do it the way I'm doing it today.  I just wanted to make sure I wasn't missing out on a better way.

**Comment by grserwe** [comment]
I like the new feature of global styles :)  Thanks!
