### ISSUE TITLE
Feature request: Global Styles

### ISSUE THREAD

**Issue by chanan** [chanan/BlazorStyled#74]
Is there a way to support something along the lines of:

MainLayout.cs:

```
<Styled GlobalStyle="ColorRed">
    color: red;
</Styled>
```

SomeComponent.razor:

```
<div class="@Styled.GlobalStyles["ColorRed"]">
    Test
</div>
```

**Comment by sanchez** [comment]
Is there a way for me to apply a global style to everything based on a selector? For example could I set a global style for all anchor tags?
