### ISSUE TITLE
Generated class names

### ISSUE THREAD

**Issue by nicucomiati990** [chanan/BlazorStyled#80]
Is there a way to control the generated class names? I would prefer having an understandable class instead of it being all generated. I saw this on blazorstyled.io and thought that it might be possible.

**Comment by chanan** [comment]
Sorry, I didnt see this till now.

BlazorStyled (like Glamor, Glamorous and Emotion in the JS world) control the class name to work. However you can add a label to the css that will be appended to your classname:

```
<Styled @Bind-Classname="@MyClass">
  label: some-label;
  color: red;
</Styled>
```

This will generate a class with the words "-some-label" appended at the end of it.
