### ISSUE TITLE
Demo site documentation update for Server Side Blazor

### ISSUE THREAD

**Issue by topanoe** [chanan/BlazorStyled#9]
For Server Side Blazor, the install documentation needs to be updated from add:
`services.AddBlazorPrettyCode();`
to:
`services.AddBlazorStyled();`

**Comment by chanan** [comment]
The page: https://chanan.github.io/BlazorStyled/install has been updated. Thanks for finding that.

If you end up using BlazorStyled, please let me know how it goes!
