### ISSUE TITLE
Media Queries compile error

### ISSUE THREAD

**Issue by esso23** [chanan/BlazorStyled#90]
Can't compile project when using media queries. Am I doing something wrong?

Code:
```html
<Styled @bind-Classname="@ExtraSmallOnlyClass">
    @media (min-width:0px) and (max-width:599.95px) {
        display: none;
    }
</Styled>
```

Error:
```
1>...\Component1.razor(2,6,2,11): error CS0103: The name 'media' does not exist in the current context
```

Based on docs: https://blazorstyled.io/media

**Comment by chanan** [comment]
Because the @ sign is the razor symbol, you need to “encode it” by putting two @ signs: `@@media`

**Comment by esso23** [comment]
Oh, thanks. Will you update the docs or can I close the issue?

**Comment by chanan** [comment]
I will close it. I have an issue already open to review all the docs for accuracy when I publish the next version
